language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script: 
  - cd lambda-functions
  - npm install -g eslint
scripts: 
  - eslint --config=../.eslintrc */*/index.js --fix > ../eslint-result.xml

# safelist
branches:
  only:
  - master
